name: Deploy Next.js Docker Image to Dokku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for Dokku
        env:
          APP_NAME: ${{ secrets.DOKKU_PROJECT }}
        run: |
          TAG=${GITHUB_SHA}
          docker build --platform=linux/amd64 -t dokku/${APP_NAME}:${TAG} .

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Disable host key checking
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Push image to Dokku via ssh and deploy
        env:
          APP_NAME: ${{ secrets.DOKKU_PROJECT }}
          DOKKU_HOST: ${{ secrets.SSH_IP_ADDRESS }}
        run: |
          TAG=${GITHUB_SHA}

          docker image save dokku/${APP_NAME}:${TAG} | \
            ssh dokku@${DOKKU_HOST} \
              git:load-image ${APP_NAME} dokku/${APP_NAME}:${TAG}
