name: Push Next.js build to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare deploy folder
        run: |
          mkdir -p deploy
          cp -r .next public package.json deploy/
          cd deploy
          git init
          git config user.email "devolopersoroosh@gmail.com"
          git config user.name "soroosh morshedi"
          git add .
          git commit -m "Deploy prebuilt build to Dokku"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Disable host key checking
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Push to Dokku
        run: |
          cd deploy
          git remote add dokku dokku@${{ secrets.SSH_IP_ADDRESS }}:${{ secrets.DOKKU_PROJECT }} || true
          git push dokku HEAD:main -f
