name: Deploy Next.js SSR to Dokku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Next.js
      - name: Build Next.js project
        run: npm run build

      # 5️⃣ Prepare files for Dokku
      - name: Prepare files for Dokku
        run: |
          mkdir -p deploy
          cp -r .next public package*.json deploy/
          cd deploy
          git init
          git config user.email "devolopersoroosh@gmail.com"
          git config user.name "soroosh morshedi"
          git add .
          git commit -m "Deploy build to Dokku"

      # 6️⃣ Setup SSH for Dokku
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 7️⃣ Disable host key checking
      - name: Disable host key checking
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      # 8️⃣ Push to Dokku
      - name: Push to Dokku
        run: |
          cd deploy
          git remote add dokku dokku@${{ secrets.SSH_IP_ADDRESS }}:${{ secrets.DOKKU_PROJECT }} || true
          git push dokku HEAD:main -f
